export function buildHelpText(): string {
  return [
    'bond agentic cli',
    '',
    'Usage:',
    '  bun run cli -- "inspect the repo"',
    '  bun run cli -- eval --manifest evals.json --case prompt-quality',
    '  bun run cli -- eval --manifest evals.json --all',
    '  bun run cli -- autoresearch --manifest autoresearch.json --program program.md',
    '  bun run cli -- --model gpt-4.1-mini "list the files"',
    '  bun run cli -- --cwd packages/agent',
    '',
    'Flags:',
    '  --model <name>       Override OPENAI_MODEL',
    '  --compaction-model <name>',
    '                       Override OPENAI_COMPACTION_MODEL',
    '  --max-steps <n>      Max tool/model loop iterations',
    '  --auto-compact-tokens <n>',
    '                       Auto-compact once the request exceeds the estimated token limit',
    '  --timeout <ms>       Shell tool timeout in milliseconds',
    '  --cwd <path>         Working directory for the session',
    '  --manifest <path>    Eval manifest path for `eval` mode',
    '  --program <path>     Research strategy file for `autoresearch` mode',
    '  --case <id>          Run one eval case',
    '  --all                Run all eval cases in the manifest',
    '  --max-experiments <n>',
    '                       Max experiments for `autoresearch` mode',
    '  --forever            Keep running autoresearch until interrupted',
    '  --output <path>      Output JSON report path, or directory when combined with --all',
    '                       Defaults to .autoresearch/<tag> for autoresearch runs',
    '  --resume             Resume an existing autoresearch run',
    '  --tag <value>        Override the autoresearch branch/run tag',
    '  --judge-model <name> Override all judge models',
    '  --judge-model-architecture <name>',
    '                       Override the architecture critic model',
    '  --judge-model-correctness <name>',
    '                       Override the correctness critic model',
    '  --judge-model-simplicity <name>',
    '                       Override the simplicity critic model',
    '  --judge-model-goal <name>',
    '                       Override the goal critic model',
    '  -h, --help           Show this help text',
    '',
    'Environment:',
    '  OPENAI_API_KEY       Required for the default OpenAI client',
    '  OPENAI_AUTO_COMPACT_TOKENS',
    '                       Optional estimated token limit for automatic compaction',
    '  OPENAI_MODEL         Required unless --model is passed',
    '  OPENAI_COMPACTION_MODEL',
    '                       Optional model override for compaction turns',
    '  OPENAI_JUDGE_MODEL',
    '                       Optional shared model override for all eval judges',
    '  OPENAI_JUDGE_MODEL_ARCHITECTURE',
    '                       Optional model override for the architecture critic',
    '  OPENAI_JUDGE_MODEL_CORRECTNESS',
    '                       Optional model override for the correctness critic',
    '  OPENAI_JUDGE_MODEL_SIMPLICITY',
    '                       Optional model override for the simplicity critic',
    '  OPENAI_JUDGE_MODEL_GOAL',
    '                       Optional model override for the goal critic',
    '  OPENAI_BASE_URL      Optional override for Responses API-compatible APIs',
  ].join('\n');
}
